# Generated by Django 6.0.1 on 2026-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Личный инвайт-код'),
        ),
    ]
